---
title: A Cosmology Group
longtitle: A Cosmology Group - Observations, inferences and the fading confidence in Î›CDM cosmology
remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
plugins:
  - jekyll-remote-theme
---
